### ISSUE TITLE
GLSL version

### ISSUE THREAD

**Issue by fogg928s4** [cococry/leif#18]
Hello, so I am currently following learning about the library's functionality (more specifically with the task manager project). After writing the first lines of code and linking during compilation I was met with this error
`
```
[LEIF ERROR]: Failed to compile vertex shader.
Leif: [INFO]: 0:1(10): error: GLSL 4.60 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 4.00, 4.10, 4.20, 4.30, 4.40, 4.50, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

[LEIF ERROR]: Failed to compile fragment shader.
Leif: [INFO]: 0:1(10): error: GLSL 4.60 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 4.00, 4.10, 4.20, 4.30, 4.40, 4.50, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES
```
Afaik it has to do with the graphics drivers and OpenGL version, but upon further inspection using `glxinfo | grep "OpenGL"` the output returns version 4.5 (compatibility profile) which should match the GLSL version running.

**Comment by cococry** [comment]
i changed the version to 450 now as there will multiple issues regarding this problem and 460 is not needed. 

does that fix it?

**Comment by fogg928s4** [comment]
Thanks, I ended up using another machine that ran with no issues since I kept getting conflicting messages regarding the GLSL version that was running. For instance, I had 4.1 installed but the error message said it was running 4.6.
