### ISSUE TITLE
GLAD is platform specific

### ISSUE THREAD

**Issue by gruelingpine185** [cococry/Leif#2]
From my understanding, GLAD is platform specific. Maybe write a section in your README to let users know that they'll have to download a version for their platform from https://glad.dav1d.de/. Same principal goes to the future dependancies. I guess, in addition to above, add it to your `.gitignore` so that way everyone wont have to re-download GLAD for their system every time a change to the repo occurs.

**Comment by cococry** [comment]
Yes so eventually, the library will just be a single c and h file that you can include to your build. You then have to handle the dependencies yourself. There will probably also be compiled libraries for the different platforms with that you can link. So the glad part will be handled by the user and prebuild for the specific platform

**Comment by RHL120** [comment]
Hmm, I wonder if the have an API that can be used to download GLAD on build with curl, wget or something like that.
Would this be something you would accept?

**Comment by gruelingpine185** [comment]
I don't think they have an api for that. I was wondering the same thing too. I'll ask

**Comment by gruelingpine185** [comment]
Here is the Issue I created: https://github.com/Dav1dde/glad/issues/435

**Comment by RHL120** [comment]
> I don't think they have an api for that. I was wondering the same thing too. I'll ask

When you hit the generate button a POST request is made to /generate with the following example content:
`language=c&specification=gl&api=gl%3D4.6&api=gles1%3D1.0&api=gles2%3Dnone&api=glsc2%3Dnone&profile=compatibility&loader=on`

**Comment by gruelingpine185** [comment]
from that, i can't just tack on `...&platform=macos` can I? Is there docs for that?

**Comment by RHL120** [comment]
> from that, i can't just tack on `...&platform=macos` can I? Is there docs for that?

I don't think there is an option for macos. As a side note I don't think there is anything OS specific in there. files are just C as far as I can tell. I don't think there are any docs I just used used the network tab in the dev tools on my browser but if you would like to know more the source code would probably be a good place to start:
https://github.com/Dav1dde/glad-web/blob/f2659ebfb9e54b9d72c0cb806c8a27724f8719bf/gladweb/views/index.py#L116

**Comment by gruelingpine185** [comment]
Alr. Thx so much.

**Comment by RHL120** [comment]
This should give you back the generated url: `curl -X POST -d "language=c&specification=gl&api=gl%3D1.3&api=gles1%3Dnone&api=gles2%3Dnone&api=glsc2%3Dnone&profile=compatibility&loader=on" --max-redirs 0 https://glad.dav1d.de/generate |grep "You should" |sed -e 's|<
p>.*">||g`

**Comment by Dav1dde** [comment]
There is nothing platform specific which glad needs to know, it does not matter on which or for which platform you generate, you will always get the same sources and headers.

> PS: I don't see anything platform specific in their options but even if it is not platform specific it would be better to download the deps on-build instead of having them bundled with the repository IMHO.

I recommend you to just include the files in your repository, faster build times, less dependencies (Python + Jinja) and nice diffs when you re-generate the files.

> This should give you back the generated url:
> 
> ```shell
> curl -X POST -d "language=c&specification=gl&api=gl%3D1.3&api=gles1%3Dnone&api=gles2%3Dnone&api=glsc2%3Dnone&profile=compatibility&loader=on" --max-redirs 0 https://glad.dav1d.de/generate |grep "You should" |sed -e 's|<p>.*">||g' -e 's|</a>.*||g' | tr -d '\n'
> ```

I'd ask you not to do that, it's fine if you use this as a one (or two-) time script to regenerate automatically, but if it is integrated into your builds this will generate a bunch of files over and over on my server. It also may break when I update the website.

**Comment by gruelingpine185** [comment]
I think the response I received from the creator of GLAD says enough. Essentially they said that it isn't platform specific, but the underlying APIs and contexts are. My bad. With that in mind, This may be a good spot to close this issue. Thanks for all of your input and support to correct my misunderstanding :)

**Comment by cococry** [comment]
okay, so changing the version to 450 in the shaders made it work and didn't cause any graphical bugs?

**Comment by cococry** [comment]
okay. i will be testing this and if it does not cause any issues, will add it to leifs main branch.

**Comment by cococry** [comment]
hahaha okay didn't know that 😅
